### ISSUE TITLE
No longer able to capture promise action lifecycle anonymously

### ISSUE THREAD

**Issue by christensena** [vgmr/redux-helper#5]
I use `matchAsLinkedPromiseAction` to track which promise actions are in progress by type.

This is useful for wait cursor state e.g.
```
const reducer: Reducer<IWaitingState> = (state = defaultState, action: any) => {

  if (promiseActionStarted.matchAsLinkedPromiseAction(action)) {
    return {
      ...state,
      [action.promiseActionType]: true,
    };
  } else if (promiseActionEnded.matchAsLinkedPromiseAction(action) ||
    promiseActionErrored.matchAsLinkedPromiseAction(action)) {
    return {
      ...state,
      [action.promiseActionType]: false,
    };
  }

  return state;
};
```
There has been a breaking change in the API, adding an additional required parameter to `matchAsLinkedPromisedAction` which blocks the above scenario.

**Comment by Jodan-pz** [comment]
I'm fixing it in the next version 1.0.3.
Thank you!

**Comment by ghost** [comment]
If anything is ok I'm going to close the issue.

**Comment by christensena** [comment]
This seems to be ok now thanks.
I don't think you needed to change the signature of the `CheckedPromiseMiddlewareOptions` methods though? It seems the arg there can only ever be a promise action.
